// <auto-generated />
using System;
using FleetManagement.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetManagement.EF.Migrations
{
    [DbContext(typeof(ReferralDbContext))]
    [Migration("20251128004207_Jsonfix")]
    partial class Jsonfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetManagement.EF.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AltPhone")
                        .HasColumnType("text")
                        .HasColumnName("AltPhone");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text")
                        .HasColumnName("CompanyName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<string>("PositionTitle")
                        .HasColumnType("text")
                        .HasColumnName("PositionTitle");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Contact", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("AvatarUrl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<DateTime?>("DriverLicenseExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DriverLicenseExpiry");

                    b.Property<string>("DriverLicenseNumber")
                        .HasColumnType("text")
                        .HasColumnName("DriverLicenseNumber");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<long?>("FleetId")
                        .HasColumnType("bigint")
                        .HasColumnName("FleetId");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("UserId");

                    b.ToTable("Driver", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Fleet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("Code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("ParentId");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("VendorId");

                    b.ToTable("Fleet", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BaseAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("BaseAmount");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CancelledAt");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CompletedAt");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("ContactId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("Currency");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<long>("DestinationPlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("DestinationPlaceId");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DispatchedAt");

                    b.Property<long?>("DriverId")
                        .HasColumnType("bigint")
                        .HasColumnName("DriverId");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<long>("OriginPlaceId")
                        .HasColumnType("bigint")
                        .HasColumnName("OriginPlaceId");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("Payload");

                    b.Property<string>("PodMethod")
                        .HasColumnType("text")
                        .HasColumnName("PodMethod");

                    b.Property<string>("PublicId")
                        .HasColumnType("text")
                        .HasColumnName("PublicId");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ScheduledAt");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("TotalAmount");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("text")
                        .HasColumnName("TrackingNumber");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<long?>("VehicleId")
                        .HasColumnType("bigint")
                        .HasColumnName("VehicleId");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("DestinationPlaceId");

                    b.HasIndex("DriverId");

                    b.HasIndex("OriginPlaceId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VendorId");

                    b.ToTable("Order", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Place", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("AddressLine2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("City");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint")
                        .HasColumnName("ContactId");

                    b.Property<string>("ContactName")
                        .HasColumnType("text")
                        .HasColumnName("ContactName");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("Country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("Longitude");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("PostalCode");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("State");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("Timezone");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("VendorId");

                    b.ToTable("Place", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.StoredDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ContentType");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("OriginalFileName");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeBytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("StoragePath");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UploadedAtUtc");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("UploadedBy");

                    b.HasKey("Id");

                    b.ToTable("StoredDocuments", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("Amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("Currency");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<string>("LineItems")
                        .HasColumnType("text")
                        .HasColumnName("LineItems");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("OrderId");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text")
                        .HasColumnName("PaymentMethod");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ProcessedAt");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("Reference");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Transaction", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("LastName");

                    b.Property<string>("MobilePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("MobilePhoneNumber");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.UserLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("PasswordHash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("Capacity");

                    b.Property<string>("CapacityUnit")
                        .HasColumnType("text")
                        .HasColumnName("CapacityUnit");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal?>("CurrentOdometer")
                        .HasColumnType("numeric")
                        .HasColumnName("CurrentOdometer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<long?>("DriverId")
                        .HasColumnType("bigint")
                        .HasColumnName("DriverId");

                    b.Property<long?>("FleetId")
                        .HasColumnType("bigint")
                        .HasColumnName("FleetId");

                    b.Property<string>("FuelType")
                        .HasColumnType("text")
                        .HasColumnName("FuelType");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<string>("Make")
                        .HasColumnType("text")
                        .HasColumnName("Make");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("Model");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("text")
                        .HasColumnName("PlateNumber");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("VendorId")
                        .HasColumnType("bigint")
                        .HasColumnName("VendorId");

                    b.Property<string>("Vin")
                        .HasColumnType("text")
                        .HasColumnName("Vin");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("Year");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("FleetId");

                    b.HasIndex("VendorId");

                    b.ToTable("Vehicle", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Vendor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasColumnType("text")
                        .HasColumnName("BillingAddress");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("InternalId");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("Metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("Website");

                    b.HasKey("Id");

                    b.ToTable("Vendor", "public");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Driver", b =>
                {
                    b.HasOne("FleetManagement.EF.Models.Fleet", "Fleet")
                        .WithMany("Drivers")
                        .HasForeignKey("FleetId");

                    b.HasOne("FleetManagement.EF.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Fleet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Fleet", b =>
                {
                    b.HasOne("FleetManagement.EF.Models.Fleet", "ParentFleet")
                        .WithMany("ChildFleets")
                        .HasForeignKey("ParentId");

                    b.HasOne("FleetManagement.EF.Models.Vendor", "Vendor")
                        .WithMany("Fleets")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentFleet");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Order", b =>
                {
                    b.HasOne("FleetManagement.EF.Models.Contact", "Contact")
                        .WithMany("Orders")
                        .HasForeignKey("ContactId");

                    b.HasOne("FleetManagement.EF.Models.Place", "DestinationPlace")
                        .WithMany("DestinationOrders")
                        .HasForeignKey("DestinationPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManagement.EF.Models.Driver", "Driver")
                        .WithMany("Orders")
                        .HasForeignKey("DriverId");

                    b.HasOne("FleetManagement.EF.Models.Place", "OriginPlace")
                        .WithMany("OriginOrders")
                        .HasForeignKey("OriginPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManagement.EF.Models.Vehicle", "Vehicle")
                        .WithMany("Orders")
                        .HasForeignKey("VehicleId");

                    b.HasOne("FleetManagement.EF.Models.Vendor", "Vendor")
                        .WithMany("Orders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("DestinationPlace");

                    b.Navigation("Driver");

                    b.Navigation("OriginPlace");

                    b.Navigation("Vehicle");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Place", b =>
                {
                    b.HasOne("FleetManagement.EF.Models.Contact", "Contact")
                        .WithMany("Places")
                        .HasForeignKey("ContactId");

                    b.HasOne("FleetManagement.EF.Models.Vendor", "Vendor")
                        .WithMany("Places")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Transaction", b =>
                {
                    b.HasOne("FleetManagement.EF.Models.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.UserLogin", b =>
                {
                    b.HasOne("FleetManagement.EF.Models.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Vehicle", b =>
                {
                    b.HasOne("FleetManagement.EF.Models.Driver", "Driver")
                        .WithMany("VehiclesAsCurrentDriver")
                        .HasForeignKey("DriverId");

                    b.HasOne("FleetManagement.EF.Models.Fleet", "Fleet")
                        .WithMany("Vehicles")
                        .HasForeignKey("FleetId");

                    b.HasOne("FleetManagement.EF.Models.Vendor", "Vendor")
                        .WithMany("Vehicles")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Fleet");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Contact", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Driver", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("VehiclesAsCurrentDriver");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Fleet", b =>
                {
                    b.Navigation("ChildFleets");

                    b.Navigation("Drivers");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Order", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Place", b =>
                {
                    b.Navigation("DestinationOrders");

                    b.Navigation("OriginOrders");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.User", b =>
                {
                    b.Navigation("Logins");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Vehicle", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FleetManagement.EF.Models.Vendor", b =>
                {
                    b.Navigation("Fleets");

                    b.Navigation("Orders");

                    b.Navigation("Places");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
